In [2]:
# <!-- Add/Sub/Mul/Div -->
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
arr + 2

array([3, 4, 5, 6, 7])

In [4]:
arr - 2

array([-1,  0,  1,  2,  3])

In [5]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [6]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5])

# Slicing in array

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr[2]

3

In [9]:
arr[1:2]

array([2])

In [10]:
arr2 = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr2.reshape(2, 3)
print("Reshaped Array:\n", reshaped)

transposed = reshaped.T
print("Transposed Array:\n", transposed)


Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [11]:
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))


Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [12]:
int_array = np.array([1, 2, 3], dtype=int)
float_array = np.array([1.1, 2.2, 3.3], dtype=float)
bool_array = np.array([True, False, True], dtype=bool)
str_array = np.array(["a", "b", "c"], dtype=str)

print("Integer Array:", int_array)
print("Float Array:", float_array)
print("Boolean Array:", bool_array)
print("String Array:", str_array)


Integer Array: [1 2 3]
Float Array: [1.1 2.2 3.3]
Boolean Array: [ True False  True]
String Array: ['a' 'b' 'c']


In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concatenated = np.concatenate((arr1, arr2))
print("Concatenated Array:", concatenated)


Concatenated Array: [1 2 3 4 5 6]


In [14]:
unsorted_array = np.array([3, 1, 2, 5, 4])

ascending = np.sort(unsorted_array)
print("Ascending Order:", ascending)

descending = np.sort(unsorted_array)[::-1]
print("Descending Order:", descending)


Ascending Order: [1 2 3 4 5]
Descending Order: [5 4 3 2 1]


In [15]:
import pandas as pd
import json


In [16]:
df = pd.read_csv('retail supermarket.csv')

In [17]:
df

Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky   
1       Second Class   Consumer  United States        Henderson    Kentucky   
2       Second Class  Corporate  United States      Los Angeles  California   
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
...              ...        ...            ...              ...         ...   
9989    Second Class   Consumer  United States            Miami     Florida   
9990  Standard Class   Consumer  United States       Costa Mesa  California   
9991  Standard Class   Consumer  United States       Costa Mesa  California   
9992  Standard Class   Consumer  United States       Costa Mesa  California   
9993    Second Class   Consumer  United States      Westminster  California   

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2   
1           42420  South        Furniture       Chairs  731.9400         3   
2           90036   West  Office Supplies       Labels   14.6200         2   
3           33311  South        Furniture       Tables  957.5775         5   
4           33311  South  Office Supplies      Storage   22.3680         2   
...           ...    ...              ...          ...       ...       ...   
9989        33180  South        Furniture  Furnishings   25.2480         3   
9990        92627   West        Furniture  Furnishings   91.9600         2   
9991        92627   West       Technology       Phones  258.5760         2   
9992        92627   West  Office Supplies        Paper   29.6000         4   
9993        92683   West  Office Supplies   Appliances  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.00   13.3200  
9993      0.00   72.9480  

[9994 rows x 13 columns]

In [18]:
df.head()


Ship Mode    Segment        Country             City       State  \
0    Second Class   Consumer  United States        Henderson    Kentucky   
1    Second Class   Consumer  United States        Henderson    Kentucky   
2    Second Class  Corporate  United States      Los Angeles  California   
3  Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4  Standard Class   Consumer  United States  Fort Lauderdale     Florida   

   Postal Code Region         Category Sub-Category     Sales  Quantity  \
0        42420  South        Furniture    Bookcases  261.9600         2   
1        42420  South        Furniture       Chairs  731.9400         3   
2        90036   West  Office Supplies       Labels   14.6200         2   
3        33311  South        Furniture       Tables  957.5775         5   
4        33311  South  Office Supplies      Storage   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164

In [20]:
df.shape

(9994, 13)

In [34]:
df.dtypes["Sales"]

dtype('float64')

In [37]:
df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [38]:
df.describe()

Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000